### ISSUE TITLE
Redoing IT ...

### ISSUE THREAD

**Issue by nazimboudeffa** [yu1l/Facebook_like_website#23]
Hello,
Do you think you can redoit again ?
I have asked you some questions on Livecoding.TV about dependecies of the thechnologies you are using. You said Yes and No :8ball: i didn't unerstood
Regards.

**Comment by yhoshino11** [comment]
Hello !
Sorry for being late !
Of course, I can redoit again because all development process is saved on Github & Livecoding.tv :)
Also, you can make this by yourself by watching my livecoding again !
I'm willing to help you when you confronted in any problem !

**Comment by boudeffa** [comment]
Tnhak you
see you later on LCTV
Best regards

**Comment by boudeffa** [comment]
Oh!
I want to thank you for trying this, it's not closed in fact and here is a way to do reDo this software

https://soundcloud.com/dj-kheops-officiel/dj-kheops-mix-live-new-rb-2

what do you think ?
