### ISSUE TITLE
secure chat

### ISSUE THREAD

**Issue by yu1l** [yu1l/Facebook_like_website#61]
RedPandaadd secure chat  :P
RedPandawith end-to-end encryption

**Comment by CallumCarmicheal** [comment]
Assign me to the issue ;)

Working on the p2s chat system now. (Peer to Server) System, the packets/messages between the server will automatically be secured by SSL, if not i will add a encryption method were the data will be hashed by the username and login-ID (The login HASH)

* Also still waiting on that ;)
